// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdycbapyjihfvkloetlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkeWNiYXB5amloZnZrbG9ldGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzU1OTQsImV4cCI6MjA3MDc1MTU5NH0.FfRALiOpdb_z-BTHZEJiiQ4ol1fVWYhpXGaU0boSldM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});